name: MLCOURSE
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=1.4.2
  - pytorch=1.10.2
  - scikit-learn=1.0.2
  - seaborn=0.11.2
  - tqdm=4.64.0
  - statsmodels=0.13.2
  - ta=0.10.1
  - graphviz=2.50.0
  - xgboost=1.5.0
  - pip
  - pip:
      - gym==0.24.0
      - notebook==6.4.12
      - ipywidgets==7.7.1
      - matplotlib==3.5.2
      - scipy==1.8.1
      - pandas-datareader==0.10.0
      - python-binance==1.0.16
      - kneed==0.7.0
      - hmmlearn==0.2.7
      - pyhhmm==2.0.1
      - ta==0.10.1
      - polars==1.33.1
      - pyarrow==21.0.0
